# Generated by Django 3.2.15 on 2022-09-02 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('ususario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('token', models.CharField(max_length=10)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('deta_validade', models.DateField()),
            ],
        ),
    ]
