# Generated by Django 3.2.15 on 2022-11-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221026_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valores',
            options={'verbose_name': 'Valor', 'verbose_name_plural': 'Valores'},
        ),
    ]
