# Generated by Django 3.2.15 on 2022-08-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_auto_20220823_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='bairro',
            name='designacao',
            field=models.CharField(default='', max_length=255),
        ),
    ]
