# Generated by Django 3.2.15 on 2022-08-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0004_bairro_designacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bairro',
            name='update_date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='update_date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
