# Generated by Django 3.2.15 on 2022-08-23 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0005_auto_20220823_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('data_actualizacao', models.DateField(auto_created=True, blank=True, null=True)),
                ('data_criacao', models.DateField(auto_created=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('ficheiro', models.ImageField(upload_to='imagens')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEntidade',
            fields=[
                ('data_actualizacao', models.DateField(auto_created=True, blank=True, null=True)),
                ('data_criacao', models.DateField(auto_created=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('designacao', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Entidade',
                'verbose_name_plural': 'Tipos de Entidade',
            },
        ),
        migrations.RenameField(
            model_name='bairro',
            old_name='update_date',
            new_name='data_actualizacao',
        ),
        migrations.RenameField(
            model_name='bairro',
            old_name='create_date',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='cidade',
            old_name='update_date',
            new_name='data_actualizacao',
        ),
        migrations.RenameField(
            model_name='cidade',
            old_name='create_date',
            new_name='data_criacao',
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('data_actualizacao', models.DateField(auto_created=True, blank=True, null=True)),
                ('data_criacao', models.DateField(auto_created=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('rua_avenida', models.CharField(max_length=255)),
                ('quarteirao', models.CharField(blank=True, max_length=10, null=True)),
                ('nome_edificio', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_edificio', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.bairro')),
            ],
            options={
                'verbose_name': 'Localizacao',
                'verbose_name_plural': 'Localizacoes',
            },
        ),
    ]
