# Generated by Django 3.2.15 on 2022-08-23 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0007_pessoa_tipodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='apelido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reg.imagem'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nuit',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
