# Generated by Django 3.2.15 on 2022-08-24 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reg', '0008_auto_20220823_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('data_actualizacao', models.DateField(auto_created=True, blank=True, null=True)),
                ('data_criacao', models.DateField(auto_created=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('nuit', models.CharField(blank=True, max_length=9, null=True)),
                ('nome', models.CharField(max_length=500)),
                ('foto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reg.imagem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoOrganizacao',
            fields=[
                ('data_actualizacao', models.DateField(auto_created=True, blank=True, null=True)),
                ('data_criacao', models.DateField(auto_created=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('designacao', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Organizacao',
                'verbose_name_plural': 'Tipos de Organizacoes',
            },
        ),
        migrations.AlterModelOptions(
            name='tipoentidade',
            options={'verbose_name': 'Tipo de Entidade', 'verbose_name_plural': 'Tipos de Entidades'},
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='data_actualizacao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='nuit',
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('data_actualizacao', models.DateField(auto_created=True, blank=True, null=True)),
                ('data_criacao', models.DateField(auto_created=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('numero_casa', models.CharField(blank=True, max_length=10)),
                ('andar', models.CharField(blank=True, max_length=10)),
                ('flat', models.CharField(blank=True, max_length=10)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField(blank=True)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.entidade')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.localizacao')),
            ],
            options={
                'verbose_name': 'Endereco',
                'verbose_name_plural': 'Enderecos',
            },
        ),
        migrations.AddField(
            model_name='pessoa',
            name='entidade_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reg.entidade'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('entidade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reg.entidade')),
                ('data_publicacao', models.DateTimeField(auto_created=True, blank=True)),
                ('data_constituicao', models.DateTimeField(auto_created=True, blank=True)),
                ('abreviatura', models.CharField(blank=True, max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('numero_br', models.CharField(blank=True, max_length=255)),
                ('admin_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.tipoorganizacao')),
            ],
            options={
                'verbose_name': 'organizacao',
                'verbose_name_plural': 'organizacacoes',
            },
            bases=('reg.entidade',),
        ),
    ]
