# Generated by Django 3.2.15 on 2022-08-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0010_auto_20220824_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
    ]
