# Generated by Django 3.2.15 on 2022-10-03 08:29

import apps.reg.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0014_auto_20221003_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='ficheiro',
            field=models.ImageField(null=True, upload_to=apps.reg.models.get_upload_path),
        ),
    ]
