# Generated by Django 3.2.15 on 2022-10-06 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reg', '0015_alter_imagem_ficheiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('data_actualizacao', models.DateField(auto_created=True, blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('numero', models.CharField(max_length=25)),
                ('data_inicio_contrato', models.DateField(default=django.utils.timezone.now)),
                ('data_assinatura', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.BooleanField(default=True)),
                ('contratante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reg.organizacao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModificadoresContrato',
            fields=[
                ('data_actualizacao', models.DateField(auto_created=True, blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('designacao', models.CharField(max_length=255, null=True)),
                ('usuario_criacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'modificador de contrato',
                'verbose_name_plural': 'modificadores de contrato',
            },
        ),
        migrations.AlterField(
            model_name='entidade',
            name='foto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reg.imagem'),
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('data_actualizacao', models.DateField(auto_created=True, blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('designacao', models.CharField(max_length=255, null=True)),
                ('usuario_criacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tipo de contrato',
                'verbose_name_plural': 'tipos de contrato',
            },
        ),
        migrations.CreateModel(
            name='PrazoContrato',
            fields=[
                ('data_actualizacao', models.DateField(auto_created=True, blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('data_termino', models.DateField(default=django.utils.timezone.now)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reg.contrato')),
                ('modificador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reg.modificadorescontrato')),
                ('usuario_criacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reg.tipocontrato'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='usuario_criacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('contrato_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reg.contrato')),
                ('contratado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.pessoa')),
            ],
            options={
                'abstract': False,
            },
            bases=('reg.contrato',),
        ),
    ]
