# Generated by Django 3.2.15 on 2022-10-10 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0016_auto_20221006_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='tipo_documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reg.tipodocumento'),
        ),
    ]
