# Generated by Django 3.2.15 on 2022-10-11 10:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0017_alter_pessoa_tipo_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='estado',
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_termino',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contrato',
            name='modificador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reg.modificadorescontrato'),
        ),
    ]
