# Generated by Django 3.2.15 on 2022-11-22 07:47

import apps.projectos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectos', '0002_auto_20221118_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecto',
            name='imagem',
            field=models.ImageField(null=True, upload_to=apps.projectos.models.get_upload_path),
        ),
    ]
