# Generated by Django 3.2.15 on 2022-12-09 06:47

import apps.projectos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectos', '0003_alter_projecto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectogaleria',
            name='imagem',
            field=models.ImageField(upload_to=apps.projectos.models.get_upload_path_galeria),
        ),
    ]
